### ISSUE TITLE
Mejorando el espacio de trabajo en Slack

### ISSUE THREAD

**Issue by limcross** [Ticketplus/guides#8]
Slack es nuestro espacio de trabajo, debemos sacarle el máximo provecho a este. Si conseguimos establecer una comunicación efectiva, en el futuro no será necesario encontrarse en la oficina para trabajar de forma eficiente.

## Descripción
Hoy en día alguno de nosotros contamos con más de 45 canales, muchos de ellos creados sin un objetivo claro, por lo que se hace imposible establecer hitos tras los que establecer un cierre (archivado) del canal.

## Posible Solución
Slack propone que un espacio de trabajo óptimo se consigue manteniendo los canales en los que se trabaja al mínimo, siendo 8 canales lo óptimo, para conseguir esto y mejorar entre otras cosas el espacio de trabajo, propongo:

* **Establecer una convención de nombres para nombrar los canales**
  Basándose en la convención de nombre propuesta por [Slack](https://downloads.slack-edge.com/blog/Channel+Naming+Conventions.pdf), propongo que:
    * Para los proyectos en curso, se comiencen los nombres con `#proj-`
    * Que equipo cuente con su espacio de trabajo interno para discutir su trabajo, anteponiendo el prefijo `#team-`, así `#team-ti` será nuestro espacio de trabajo.
    * Crear espacios de trabajo inter área con `#help-` para que puedan resolver dudas, o escalar problemas.
    * Usar `#notify-` para establecer canales de notificaciones como `#notify-bugsnag`
    * Para llevar un registro de las cuentas y los clientes se anteponga el prefijo `#client-`
    * Establecer canales por ubicación (para cuando tengamos varias oficinas 🙄) mediante `#brasil-news`.
   * Motivar la creación de canales para temas de ocio como `#futbol`, `#got`.
* **Todos los canales deben contar con un propósito definido**
* **Reducir los canales de notificación al mínimo**
  Agruparlos indiferente de la aplicación y el ambiente en el que se encuentren, es decir los canales **#cashless-prod-bugsnag**, **#cashless-stg-bugsnag**, **#core-prod-bugsnag**, etc, podrían ser migrados a unúnicoo canal llamado **#notify-bugsnag**
* **Establecer buenas prácticas en el uso de Slack**
  * [Deja que tu equipo sepa tus horas de trabajo](https://slack.com/intl/es-es/slack-tips/let-your-team-know-your-working-hours)
  * [Formatea los mensajes para facilitar y hacer más atractiva su lectura](https://slackhq.com/slack-essentials-getting-the-most-out-of-messaging#format)
  * [Notifica a las personas clave con una @mention](https://slackhq.com/slack-essentials-getting-the-most-out-of-messaging#mention)
  * Comparte código usando Snippets.
  * Agiliza tu comunicación haciendo uso de las video llamadas.
  * [Organiza tu discusión en un hilo](https://slackhq.com/slack-essentials-getting-the-most-out-of-messaging#threads).
  * [Comparte una conversación pasada en lugar de mencionarlo en ella](https://slackhq.com/slack-essentials-getting-the-most-out-of-messaging#share).
  * [Responde rápidamente con emojis](https://slackhq.com/slack-essentials-getting-the-most-out-of-messaging#emoji).
  * Si tienes alguna duda, prefiere los canales en lugar del DM.
* ~~**Prohibir la comunicación por DM**~~... 😒 Ok no.

_Una gran colaboración es posible solo con una gran comunicación._

**Comment by felmsena** [comment]
En general me gusta todo, solo me llama la atención lo siguiente:

> Reducir los canales de notificación al mínimo
Agruparlos indiferente de la aplicación y el ambiente en el que se encuentren, es decir los canales #cashless-prod-bugsnag, #cashless-stg-bugsnag, #core-prod-bugsnag, etc, podrían ser migrados a un único canal llamado #notify-bugsnag

Me agrada más agruparlos por nivel de desarrollo, como #notify-bugsnag-prod, #notify-bugsnag-develop.

**Comment by roanvilina** [comment]
Me gusta bastante la propuesta. Me gustaría que como conclusión se generaran dos registros:

1. En un archivo o sección específica de slack una descripción como esta y los links a recursos de utilidad
2. Un pequeño bulleteo de las ideas principales en un archivo o sección que resuma todas las buenas prácticas de distintos lenguajes y herramientas.

Con los canales de notificación me pasa que de repente me gustaría una alternativa más resumida, quizá no es necesario ver todos los cambios de cada tarjeta (y de las propias uno puede llevar cuenta digamos), pero sí quizá cada tanto (una o algunas veces al día) recibir un resumen de lo que se ha movido, migrado, etc; no sé si es posible.

**Comment by limcross** [comment]
> En general me gusta todo, solo me llama la atención lo siguiente:
> 
> > Reducir los canales de notificación al mínimo
> > Agruparlos indiferente de la aplicación y el ambiente en el que se encuentren, es decir los canales #cashless-prod-bugsnag, #cashless-stg-bugsnag, #core-prod-bugsnag, etc, podrían ser migrados a un único canal llamado #notify-bugsnag
> 
> Me agrada más agruparlos por nivel de desarrollo, como #notify-bugsnag-prod, #notify-bugsnag-develop.

Es básicamente lo mismo 🤔

**Comment by felmsena** [comment]
> > En general me gusta todo, solo me llama la atención lo siguiente:
> > > Reducir los canales de notificación al mínimo
> > > Agruparlos indiferente de la aplicación y el ambiente en el que se encuentren, es decir los canales #cashless-prod-bugsnag, #cashless-stg-bugsnag, #core-prod-bugsnag, etc, podrían ser migrados a un único canal llamado #notify-bugsnag
> > 
> > 
> > Me agrada más agruparlos por nivel de desarrollo, como #notify-bugsnag-prod, #notify-bugsnag-develop.
> 
> Es básicamente lo mismo 🤔

Arriba por lo que escribiste, pareciera que quieres juntar todos los proyectos en un canal. Yo sugiero dos canales, uno de producción con todos los proyectos y otro de desarrollo con lo mismo.

**Comment by limcross** [comment]
> > > En general me gusta todo, solo me llama la atención lo siguiente:
> > > > Reducir los canales de notificación al mínimo
> > > > Agruparlos indiferente de la aplicación y el ambiente en el que se encuentren, es decir los canales #cashless-prod-bugsnag, #cashless-stg-bugsnag, #core-prod-bugsnag, etc, podrían ser migrados a un único canal llamado #notify-bugsnag
> > > 
> > > 
> > > Me agrada más agruparlos por nivel de desarrollo, como #notify-bugsnag-prod, #notify-bugsnag-develop.
> > 
> > 
> > Es básicamente lo mismo 🤔
> 
> Arriba por lo que escribiste, pareciera que quieres juntar todos los proyectos en un canal. Yo sugiero dos canales, uno de producción con todos los proyectos y otro de desarrollo con lo mismo.

Ahh, entiendo. Bueno creo que podría ser útil, eso si me preocupa que caigamos en ignorar canales por no tratarse de producción.
